version: 1.0.0

port: 9999

openai:
  apikey: OPENAI_APIKEY
  org:
  proxy: http://172.26.128.1:1080

log:
  # 支持debug(-1)、info(0)、warn(1)、error(2)、dpanic(3)、panic(4)、fatal(5)
  level: 0 

redis:
  addr: localhost:6379
  db: 0
  password: PASSWORD
  expire: 600

wechat:
  token: chatGPT
  appID: APPID
  appsecret: APPSECRET