version: 1.0.0

port: 9999

openai:
  # 支持OpenAI_APIKEY和accessToken，优先使用OPENAI_APIKEY，要使用accessToken，OPENAI_APIKEY需要设置为空
  apikey: OPENAI_APIKEY
  org:
  proxy: http://172.26.128.1:1080
  # 在浏览器中登录 https://chat.openai.com/chat后访问https://chat.openai.com/api/auth/session获取
  accessToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZCTWpkQ05UZzVNRFUxUlRVd1FVSkRNRU13UmtGRVFrRXpSZyJ9.eyJodHRwczovL2FwaS5vcGVuYWkuY29tL3Byb2ZpbGUiOnsiZW1haWwiOiJtZW5nYmluMTk5MkBvdXRsb29rLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlfSwiaHR0cHM6Ly9hcGkub3BlbmFpLmNvbS9hdXRoIjp7InVzZXJfaWQiOiJ1c2VyLUpTUWdyMmhiMnp4T2hROVRlQ2dpSnViWiJ9LCJpc3MiOiJodHRwczovL2F1dGgwLm9wZW5haS5jb20vIiwic3ViIjoiYXV0aDB8NjNmMTljZGRkYjA0ZjhjNmY5NjExNzc1IiwiYXVkIjpbImh0dHBzOi8vYXBpLm9wZW5haS5jb20vdjEiLCJodHRwczovL29wZW5haS5vcGVuYWkuYXV0aDBhcHAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTY4NjExODExMSwiZXhwIjoxNjg3MzI3NzExLCJhenAiOiJUZEpJY2JlMTZXb1RIdE45NW55eXdoNUU0eU9vNkl0RyIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwgbW9kZWwucmVhZCBtb2RlbC5yZXF1ZXN0IG9yZ2FuaXphdGlvbi5yZWFkIG9yZ2FuaXphdGlvbi53cml0ZSJ9.Z8yOxZvibPJfU48JkN5vK_hS6e_-Y8vQAyLPqEJjgsErNixQRYF0ZnT7RIa-gAl_NFQyVwCpUsiJBtYr-kHPMg6G6C3MnaEnD_bU-_Ubj3MuC7eYyGgt5Oj73JUuxxyEKSMFqbrrkGAwXYyvik9n3kTESjLKqNSTYpeMq6Gg6Vw-b-bCw9mk_90YRz1YC99KhH7B8AhUHuTseiFIJRl2qztM8JQCMrbZhK-OohFwqlzZnbJsHdWyUMYcbCFqzuy0chbNeQp76LPI3Z2-En5uqFgChPjCEgEi9O9sPBLAQ9-ntx_EfwbCFb9zjyC99JWQaVw0WjEJl-Y7bUedxH7_PA

log:
  # 支持debug(-1)、info(0)、warn(1)、error(2)、dpanic(3)、panic(4)、fatal(5)
  level: 0 

redis:
  addr: localhost:6379
  db: 0
  password: PASSWORD
  expire: 600